"""
AEONRIFT Recovery Planner & Failure Diagnostics Engine

Synthesizes causal recovery plans (REPLAY, REPAIR, REPLAN, COMPENSATE)
and calculates recovery confidence metrics.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Tuple
from aeonrift.core.events import ExecutionEvent, EventType, SideEffectType
from aeonrift.core.graph import CausalStateGraph
from aeonrift.core.ledger import SideEffectLedger
from aeonrift.core.policy import RollbackGuard


class FailureCategory(str, Enum):
    TOOL_FAILURE = "TOOL_FAILURE"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    AUTH_FAILURE = "AUTH_FAILURE"
    STATE_CORRUPTION = "STATE_CORRUPTION"
    LLM_FAILURE = "LLM_FAILURE"
    ENVIRONMENT_DRIFT = "ENVIRONMENT_DRIFT"
    EXTERNAL_STATE_CHANGE = "EXTERNAL_STATE_CHANGE"
    UNKNOWN = "UNKNOWN"


class RecoveryMode(str, Enum):
    REPLAY = "REPLAY"
    REPAIR = "REPAIR"
    REPLAN = "REPLAN"
    COMPENSATE = "COMPENSATE"
    ABORT = "ABORT"


@dataclass
class RecoveryPlan:
    """Actionable plan generated by AEONRIFT Recovery Planner."""
    mode: RecoveryMode
    checkpoint_id: Optional[str]
    replay_until_step: int
    recompute_from_step: int
    blocked_actions: List[str] = field(default_factory=list)
    compensation_required: bool = False
    confidence_score: float = 0.0
    explanation: str = ""


class FailureClassifier:
    """Classifies agent execution failure step into semantic failure category."""

    def classify_failure(self, failure_event: ExecutionEvent) -> FailureCategory:
        payload_str = str(failure_event.payload).lower()
        if "timeout" in payload_str or "connection" in payload_str:
            return FailureCategory.NETWORK_FAILURE
        if "unauthorized" in payload_str or "401" in payload_str or "403" in payload_str:
            return FailureCategory.AUTH_FAILURE
        if "corrupt" in payload_str or "invalid state" in payload_str:
            return FailureCategory.STATE_CORRUPTION
        if failure_event.event_type == EventType.TOOL_CALL:
            return FailureCategory.TOOL_FAILURE
        if failure_event.event_type in (EventType.LLM_CALL, EventType.LLM_RESULT):
            return FailureCategory.LLM_FAILURE
        return FailureCategory.UNKNOWN

    @classmethod
    def classify_error_message(cls, msg: str) -> FailureCategory:
        payload_str = msg.lower()
        if "timeout" in payload_str or "connection" in payload_str:
            return FailureCategory.NETWORK_FAILURE
        if "unauthorized" in payload_str or "401" in payload_str or "403" in payload_str:
            return FailureCategory.AUTH_FAILURE
        if "corrupt" in payload_str or "invalid state" in payload_str:
            return FailureCategory.STATE_CORRUPTION
        return FailureCategory.UNKNOWN


class RecoveryPlanner:
    """
    AEONRIFT Recovery Planner Engine.
    Determines optimal recovery trajectory using Causal State Graph, Side-Effect Ledger, and Rollback Guard.
    """
    def __init__(self):
        self.classifier = FailureClassifier()
        self.rollback_guard = RollbackGuard()

    def generate_plan(
        self,
        execution_id: str,
        failure_event_id: str,
        graph: CausalStateGraph,
        ledger: SideEffectLedger
    ) -> RecoveryPlan:
        """
        Synthesize recovery plan for a crashed execution trajectory.
        """
        failure_node = graph.nodes.get(failure_event_id)
        if not failure_node:
            return RecoveryPlan(
                mode=RecoveryMode.ABORT,
                checkpoint_id=None,
                replay_until_step=0,
                recompute_from_step=0,
                confidence_score=0.0,
                explanation=f"Failure event {failure_event_id} not found in causal graph."
            )

        failure_event = failure_node.event
        failure_category = self.classifier.classify_failure(failure_event)

        # 1. Locate last safe checkpoint
        cp_info = graph.find_last_safe_checkpoint(failure_event_id)
        if not cp_info:
            return RecoveryPlan(
                mode=RecoveryMode.REPLAN,
                checkpoint_id=None,
                replay_until_step=0,
                recompute_from_step=1,
                confidence_score=0.5,
                explanation="No safe checkpoint found. Re-planning required from initial state."
            )

        cp_node, cp_step = cp_info
        cp_id = cp_node.event.id

        # 2. Check for committed side effects after checkpoint
        side_effects_after_cp = graph.get_committed_side_effects_after(cp_step)
        blocked_actions = []
        has_hazard = False

        for evt in side_effects_after_cp:
            hazard = self.rollback_guard.check_rollback_hazard(evt, ledger, is_recovery_replay=True)
            if hazard.hazard_detected:
                has_hazard = True
                blocked_actions.append(evt.payload.get("tool_name", "unknown"))

        # 3. Select Recovery Mode & compute confidence score
        if failure_category == FailureCategory.AUTH_FAILURE:
            return RecoveryPlan(
                mode=RecoveryMode.REPLAN,
                checkpoint_id=cp_id,
                replay_until_step=cp_step,
                recompute_from_step=cp_step + 1,
                blocked_actions=blocked_actions,
                confidence_score=0.85,
                explanation="Authentication revoked. Re-authenticating and re-planning."
            )

        if has_hazard:
            return RecoveryPlan(
                mode=RecoveryMode.REPAIR,
                checkpoint_id=cp_id,
                replay_until_step=cp_step,
                recompute_from_step=cp_step + 1,
                blocked_actions=blocked_actions,
                compensation_required=False,
                confidence_score=0.96,
                explanation=f"Committed side-effects detected ({', '.join(blocked_actions)}). Restoring checkpoint {cp_id}, skipping/repairing side-effect step."
            )

        # Deterministic replay clean path
        return RecoveryPlan(
            mode=RecoveryMode.REPLAY,
            checkpoint_id=cp_id,
            replay_until_step=cp_step,
            recompute_from_step=cp_step + 1,
            confidence_score=0.98,
            explanation=f"Clean trajectory. Deterministic replay from checkpoint {cp_id} at step {cp_step}."
        )
